[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mcbookshelf"
version = "5.0.0"
description = "A modular library datapack for Minecraft mapmakers."
readme = "README.md"
authors = [{ name = "Bookshelf Contributors", email = "contact@gunivers.net" }]
license = { text = "MPL-2.0" }
requires-python = ">=3.14"
dependencies = ["beet>=0.118.0"]

[project.urls]
Homepage = "https://mcbookshelf.dev"
Documentation = "https://docs.mcbookshelf.dev"
Repository = "https://github.com/mcbookshelf/bookshelf"

[dependency-groups]
dev = ["mcbookshelf-tools"]

[tool.uv]
package = true
default-groups = "all"

[tool.uv.workspace]
members = ["tools"]

[tool.uv.sources]
mcbookshelf-tools = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["src/mcbookshelf"]

[tool.ruff]
src = ["src", "tools", "."]
line-length = 100

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "CPY001",
  "D100",
  "D101",
  "D102",
  "D103",
  "D104",
  "D105",
  "D107",
  "D203",
  "D213",
  "D401",
  "EM101",
  "EM102",
  "INP001",
  "S603",
  "TC001",
  "TC002",
  "TC003",
  "TRY003",
  "TRY400",
  "UP017",
]

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["E501", "PLR0913", "PLR2004", "S101"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
addopts = "--import-mode=importlib"
filterwarnings = [
  "ignore::DeprecationWarning:pathspec",
  "ignore::DeprecationWarning:click_help_colors",
]
